services:
  nodered:
    image: nodered/node-red:latest
    container_name: autoserv-nodered
    ports:
      - "1880:1880"
    volumes:
      - ./node-red-data:/data
    environment:
      env_file: .env
    restart: unless-stopped
    user: "1000:1000"
    networks:
      - autoserv-net
    
  strapi:
    image: strapi/strapi:latest
    container_name: autoserv-strapi
    restart: unless-stopped
    environment:
      DATABASE_CLIENT: sqlite
      DATABASE_NAME: strapi
      DATABASE_FILENAME: /srv/app/.tmp/data.db
      NODE_ENV: development
    volumes:
      - ./app:/srv/app
    ports:
      - "1337:1337"
    networks:
      - autoserv-net
    depends_on:
      - nodered

networks:
  autoserv-net:
    driver: bridge