http:
  routers:
    http-strapi:
      rule: Host(`strapi.ti-soft.ru`)
      entryPoints:
        - web
      service: strapi
      middlewares:
        - https-redirect

    https-strapi:
      rule: Host(`strapi.ti-soft.ru`)
      entryPoints:
        - websecure
      service: strapi
      tls:
        certResolver: myresolver

  middlewares:
    https-redirect:
      redirectScheme:
        scheme: https
        permanent: true

  services:
    strapi:
      loadBalancer:
        servers:
          - url: "http://192.168.11.101:1337"
